export enum PermissionsEnum {
  ADMIN = 'A',
  ORGANIZATION_EMPLOYEE = 'O',
  WEBSITE = 'W',
  SETTING = 'S',

  // ADMIN
  ADMIN_ALL = 'A00',
  ADMIN_LOGIN = 'A01',
  ADMIN_FETCH = 'A02',
  ADMIN_DETAILS = 'A03',
  ADMIN_CREATE = 'A04',
  ADMIN_UPDATE = 'A05',
  ADMIN_DELETE = 'A06',

  // ORGANIZATION EMPLOYEE AUTH
  ORG_EMPLOYEE_LOGIN = 'O01',
  ORG_EMPLOYEE_CHANGE_PASSWORD = 'O02',

  // HASHTAG
  HASHTAG_ALL = 'H00',
  HASHTAG_FETCH = 'H01',
  HASHTAG_DETAILS = 'H02',
  HASHTAG_CREATE = 'H03',
  HASHTAG_UPDATE = 'H04',
  HASHTAG_DELETE = 'H05',
  HASHTAG_ORDER = 'H06',
  HASHTAG_CHANGE_STATUS = 'H07',

  // incedant organization
  ORG_INCEDANT_ALL = 'OI00',
  ORG_INCEDANT_FETCH = 'OI01',
  ORG_INCEDANT_DETAILS = 'OI02',
  ORG_INCEDANT_CREATE = 'OI03',
  ORG_INCEDANT_UPDATE = 'OI04',
  ORG_INCEDANT_DELETE = 'OI05',

  // Inspection organization
  ORG_INSPECTION_ALL = 'OIS00',
  ORG_INSPECTION_FETCH = 'OIS01',
  ORG_INSPECTION_DETAILS = 'OIS02',
  ORG_INSPECTION_CREATE = 'OIS03',
  ORG_INSPECTION_UPDATE = 'OIS04',
  ORG_INSPECTION_DELETE = 'OIS05',

  // objectives Organization
  OBJECTIVE_ORG_ALL = 'OO00',
  OBJECTIVE_ORG_FETCH = 'OO01',
  OBJECTIVE_ORG_DETAILS = 'OO02',
  OBJECTIVE_ORG_CREATE = 'OO03',
  OBJECTIVE_ORG_UPDATE = 'OO04',
  OBJECTIVE_ORG_DELETE = 'OO05',
  OBJECTIVE_ORG_ORDER = 'OO06',
  OBJECTIVE_ORG_CHANGE_STATUS = 'OO07',

  // CATEGORY
  CATEGORY_ALL = 'C00',
  CATEGORY_FETCH = 'C01',
  CATEGORY_DETAILS = 'C02',
  CATEGORY_CREATE = 'C03',
  CATEGORY_UPDATE = 'C04',
  CATEGORY_DELETE = 'C05',
  CATEGORY_ORDER = 'C06',
  CATEGORY_CHANGE_STATUS = 'C07',

  // BLOG
  BLOG_ALL = 'B00',
  BLOG_FETCH = 'B01',
  BLOG_DETAILS = 'B02',
  BLOG_CREATE = 'B03',
  BLOG_UPDATE = 'B04',
  BLOG_DELETE = 'B05',
  BLOG_ORDER = 'B06',
  BLOG_CHANGE_STATUS = 'B07',

  // LOCATION
  LOCATION_ALL = 'L00',
  LOCATION_FETCH = 'L01',
  LOCATION_DETAILS = 'L02',
  LOCATION_CREATE = 'L03',
  LOCATION_UPDATE = 'L04',
  LOCATION_DELETE = 'L05',

  // Location Org
  LOCATION_ORG_ALL = 'LO00',
  LOCATION_ORG_FETCH = 'LO01',
  LOCATION_ORG_DETAILS = 'LO02',
  LOCATION_ORG_CREATE = 'LO03',
  LOCATION_ORG_UPDATE = 'LO04',
  LOCATION_ORG_DELETE = 'LO05',

  // INDUSTRY
  INDUSTRY_ALL = 'I00',
  INDUSTRY_FETCH = 'I01',
  INDUSTRY_DETAILS = 'I02',
  INDUSTRY_CREATE = 'I03',
  INDUSTRY_UPDATE = 'I04',
  INDUSTRY_DELETE = 'I05',

  // EQUIPMENT TYPE
  EQUIPMENT_TYPE_ALL = 'ET00',
  EQUIPMENT_TYPE_FETCH = 'ET01',
  EQUIPMENT_TYPE_DETAILS = 'ET02',
  EQUIPMENT_TYPE_CREATE = 'ET03',
  EQUIPMENT_TYPE_UPDATE = 'ET04',
  EQUIPMENT_TYPE_DELETE = 'ET05',

  //ORG EQUIPMENT TYPE
  ORG_EQUIPMENT_TYPE_ALL = 'OET00',
  ORG_EQUIPMENT_TYPE_FETCH = 'OET01',
  ORG_EQUIPMENT_TYPE_DETAILS = 'OET02',
  ORG_EQUIPMENT_TYPE_CREATE = 'OET03',
  ORG_EQUIPMENT_TYPE_UPDATE = 'OET04',
  ORG_EQUIPMENT_TYPE_DELETE = 'OET05',

  // FACTORY
  FACTORY_ALL = 'F00',
  FACTORY_FETCH = 'F01',
  FACTORY_DETAILS = 'F02',
  FACTORY_CREATE = 'F03',
  FACTORY_UPDATE = 'F04',
  FACTORY_DELETE = 'F05',

  //ORG FACTORY
  ORG_FACTORY_ALL = 'OF00',
  ORG_FACTORY_FETCH = 'OF01',
  ORG_FACTORY_DETAILS = 'OF02',
  ORG_FACTORY_CREATE = 'OF03',
  ORG_FACTORY_UPDATE = 'OF04',
  ORG_FACTORY_DELETE = 'OF05',

  // FACTORY ITEM
  FACTORY_ITEM_ALL = 'FI00',
  FACTORY_ITEM_FETCH = 'FI01',
  FACTORY_ITEM_DETAILS = 'FI02',
  FACTORY_ITEM_CREATE = 'FI03',
  FACTORY_ITEM_UPDATE = 'FI04',
  FACTORY_ITEM_DELETE = 'FI05',

  //org FACTORY ITEM
  ORG_FACTORY_ITEM_ALL = 'OFI00',
  ORG_FACTORY_ITEM_FETCH = 'OFI01',
  ORG_FACTORY_ITEM_DETAILS = 'OFI02',
  ORG_FACTORY_ITEM_CREATE = 'OFI03',
  ORG_FACTORY_ITEM_UPDATE = 'OFI04',
  ORG_FACTORY_ITEM_DELETE = 'OFI05',

  // TEMPLATE
  TEMPLATE_ALL = 'T00',
  TEMPLATE_FETCH = 'T01',
  TEMPLATE_DETAILS = 'T02',
  TEMPLATE_CREATE = 'T03',
  TEMPLATE_UPDATE = 'T04',
  TEMPLATE_DELETE = 'T05',

  //ORG TEMPLATE
  ORG_TEMPLATE_ALL = 'OT00',
  ORG_TEMPLATE_FETCH = 'OT01',
  ORG_TEMPLATE_DETAILS = 'OT02',
  ORG_TEMPLATE_CREATE = 'OT03',
  ORG_TEMPLATE_UPDATE = 'OT04',
  ORG_TEMPLATE_DELETE = 'OT05',

  // HAZARD TYPE
  HAZARD_TYPE_ALL = 'HT00',
  HAZARD_TYPE_FETCH = 'HT01',
  HAZARD_TYPE_DETAILS = 'HT02',
  HAZARD_TYPE_CREATE = 'HT03',
  HAZARD_TYPE_UPDATE = 'HT04',
  HAZARD_TYPE_DELETE = 'HT05',

  //ORG HAZARD TYPE
  ORG_HAZARD_TYPE_ALL = 'OHT00',
  ORG_HAZARD_TYPE_FETCH = 'OHT01',
  ORG_HAZARD_TYPE_DETAILS = 'OHT02',
  ORG_HAZARD_TYPE_CREATE = 'OHT03',
  ORG_HAZARD_TYPE_UPDATE = 'OHT04',
  ORG_HAZARD_TYPE_DELETE = 'OHT05',

  // ORG HAZARD
  ORG_HAZARD_ALL = 'OH00',
  ORG_HAZARD_FETCH = 'OH01',
  ORG_HAZARD_DETAILS = 'OH02',
  ORG_HAZARD_CREATE = 'OH03',
  ORG_HAZARD_UPDATE = 'OH04',
  ORG_HAZARD_DELETE = 'OH05',

  // methods organization
  ORG_METHOD_ALL = 'M00',
  ORG_METHOD_FETCH = 'M01',
  ORG_METHOD_DETAILS = 'M02',
  ORG_METHOD_CREATE = 'M03',
  ORG_METHOD_UPDATE = 'M04',
  ORG_METHOD_DELETE = 'M05',

  // methods
  METHOD_ALL = 'MM00',
  METHOD_FETCH = 'MM01',
  METHOD_DETAILS = 'MM02',
  METHOD_CREATE = 'MM03',
  METHOD_UPDATE = 'MM04',
  METHOD_DELETE = 'MM05',

  // ACCIDENTS TYPE
  ACCIDENTS_TYPE_ALL = 'AT00',
  ACCIDENTS_TYPE_FETCH = 'AT01',
  ACCIDENTS_TYPE_DETAILS = 'AT02',
  ACCIDENTS_TYPE_CREATE = 'AT03',
  ACCIDENTS_TYPE_UPDATE = 'AT04',
  ACCIDENTS_TYPE_DELETE = 'AT05',

  // ORG ACCIDENTS TYPE
  ORG_ACCIDENTS_TYPE_ALL = 'OAT00',
  ORG_ACCIDENTS_TYPE_FETCH = 'OAT01',
  ORG_ACCIDENTS_TYPE_DETAILS = 'OAT02',
  ORG_ACCIDENTS_TYPE_CREATE = 'OAT03',
  ORG_ACCIDENTS_TYPE_UPDATE = 'OAT04',
  ORG_ACCIDENTS_TYPE_DELETE = 'OAT05',

  // EQUIPMENT
  EQUIPMENT_ALL = 'EQ00',
  EQUIPMENT_FETCH = 'EQ01',
  EQUIPMENT_DETAILS = 'EQ02',
  EQUIPMENT_CREATE = 'EQ03',
  EQUIPMENT_UPDATE = 'EQ04',
  EQUIPMENT_DELETE = 'EQ05',

  //ORG EQUIPMENT
  ORG_EQUIPMENT_ALL = 'OEQ00',
  ORG_EQUIPMENT_FETCH = 'OEQ01',
  ORG_EQUIPMENT_DETAILS = 'OEQ02',
  ORG_EQUIPMENT_CREATE = 'OEQ03',
  ORG_EQUIPMENT_UPDATE = 'OEQ04',
  ORG_EQUIPMENT_DELETE = 'OEQ05',

  // CERTIFICATE
  CERTIFICATE_ALL = 'CF00',
  CERTIFICATE_FETCH = 'CF01',
  CERTIFICATE_DETAILS = 'CF02',
  CERTIFICATE_CREATE = 'CF03',
  CERTIFICATE_UPDATE = 'CF04',
  CERTIFICATE_DELETE = 'CF05',

  // ORGANIZATION
  ORGANIZATION_ALL = 'ORG00',
  ORGANIZATION_FETCH = 'ORG01',
  ORGANIZATION_DETAILS = 'ORG02',
  ORGANIZATION_CREATE = 'ORG03',
  ORGANIZATION_UPDATE = 'ORG04',
  ORGANIZATION_DELETE = 'ORG05',

  // LANGUAGE
  LANGUAGE_ALL = 'LANG00',
  LANGUAGE_FETCH = 'LANG01',
  LANGUAGE_DETAILS = 'LANG02',
  LANGUAGE_CREATE = 'LANG03',
  LANGUAGE_UPDATE = 'LANG04',
  LANGUAGE_DELETE = 'LANG05',

  // PROJECT TYPE
  PROJECT_TYPE_ALL = 'PT00',
  PROJECT_TYPE_FETCH = 'PT01',
  PROJECT_TYPE_DETAILS = 'PT02',
  PROJECT_TYPE_CREATE = 'PT03',
  PROJECT_TYPE_UPDATE = 'PT04',
  PROJECT_TYPE_DELETE = 'PT05',

  // PARTNER
  PARTNER_ALL = 'P00',
  PARTNER_FETCH = 'P01',
  PARTNER_DETAILS = 'P02',
  PARTNER_CREATE = 'P03',
  PARTNER_UPDATE = 'P04',
  PARTNER_DELETE = 'P05',

  // HERIKALY
  HERIKALY_ALL = 'HRK00',
  HERIKALY_FETCH = 'HRK01',
  HERIKALY_DETAILS = 'HRK02',
  HERIKALY_CREATE = 'HRK03',
  HERIKALY_UPDATE = 'HRK04',
  HERIKALY_DELETE = 'HRK05',

  // ORGANIZATION LOCATION
  ORG_LOCATION_ALL = 'OL00',
  ORG_LOCATION_FETCH = 'OL01',
  ORG_LOCATION_DETAILS = 'OL02',
  ORG_LOCATION_CREATE = 'OL03',
  ORG_LOCATION_UPDATE = 'OL04',
  ORG_LOCATION_DELETE = 'OL05',

  // PROJECT
  PROJECT_ALL = 'PJ00',
  PROJECT_FETCH = 'PJ01',
  PROJECT_DETAILS = 'PJ02',
  PROJECT_CREATE = 'PJ03',
  PROJECT_UPDATE = 'PJ04',
  PROJECT_DELETE = 'PJ05',

  // PROJECT ZONE
  PROJECT_ZONE_ALL = 'PZ00',
  PROJECT_ZONE_FETCH = 'PZ01',
  PROJECT_ZONE_DETAILS = 'PZ02',
  PROJECT_ZONE_CREATE = 'PZ03',
  PROJECT_ZONE_UPDATE = 'PZ04',
  PROJECT_ZONE_DELETE = 'PZ05',
  PROJECT_ZONE_FETCH_LOCATIONS = 'PZ06',

  // org team
  ORG_TEAM_ALL = 'OTT00',
  ORG_TEAM_FETCH = 'OTT01',
  ORG_TEAM_DETAILS = 'OTT02',
  ORG_TEAM_CREATE = 'OTT03',
  ORG_TEAM_UPDATE = 'OTT04',
  ORG_TEAM_DELETE = 'OTT05',

  // team
  TEAM_ALL = 'TT00',
  TEAM_FETCH = 'TT01',
  TEAM_DETAILS = 'TT02',
  TEAM_CREATE = 'TT03',
  TEAM_UPDATE = 'TT04',
  TEAM_DELETE = 'TT05',

  // ORGANIZATION EMPLOYEE
  ORG_EMPLOYEE_ALL = 'OE00',
  ORG_EMPLOYEE_FETCH = 'OE01',
  ORG_EMPLOYEE_DETAILS = 'OE02',
  ORG_EMPLOYEE_CREATE = 'OE03',
  ORG_EMPLOYEE_UPDATE = 'OE04',
  ORG_EMPLOYEE_DELETE = 'OE05',

  // HEADER
  HEADER_ALL = 'HD00',
  HEADER_FETCH = 'HD01',
  HEADER_DETAILS = 'HD02',
  HEADER_CREATE = 'HD03',
  HEADER_UPDATE = 'HD04',
  HEADER_DELETE = 'HD05',
  HEADER_ORDER = 'HD06',
  HEADER_CHANGE_STATUS = 'HD07',

  // POWERFUL FEATURE
  POWERFUL_FEATURE_ALL = 'PF00',
  POWERFUL_FEATURE_FETCH = 'PF01',
  POWERFUL_FEATURE_DETAILS = 'PF02',
  POWERFUL_FEATURE_CREATE = 'PF03',
  POWERFUL_FEATURE_UPDATE = 'PF04',
  POWERFUL_FEATURE_DELETE = 'PF05',
  POWERFUL_FEATURE_ORDER = 'PF06',
  POWERFUL_FEATURE_CHANGE_STATUS = 'PF07',

  // SYSTEM WORK
  SYSTEM_WORK_ALL = 'SW00',
  SYSTEM_WORK_FETCH = 'SW01',
  SYSTEM_WORK_DETAILS = 'SW02',
  SYSTEM_WORK_CREATE = 'SW03',
  SYSTEM_WORK_UPDATE = 'SW04',
  SYSTEM_WORK_DELETE = 'SW05',
  SYSTEM_WORK_ORDER = 'SW06',
  SYSTEM_WORK_CHANGE_STATUS = 'SW07',

  // HOME ABOUT US
  HOME_ABOUT_US_ALL = 'HA00',
  HOME_ABOUT_US_FETCH = 'HA01',
  HOME_ABOUT_US_DETAILS = 'HA02',
  HOME_ABOUT_US_CREATE = 'HA03',
  HOME_ABOUT_US_UPDATE = 'HA04',
  HOME_ABOUT_US_DELETE = 'HA05',
  HOME_ABOUT_US_ORDER = 'HA06',
  HOME_ABOUT_US_CHANGE_STATUS = 'HA07',

  // HOME VIEW PRICING
  HOME_VIEW_PRICING_ALL = 'HVP00',
  HOME_VIEW_PRICING_FETCH = 'HVP01',
  HOME_VIEW_PRICING_DETAILS = 'HVP02',
  HOME_VIEW_PRICING_CREATE = 'HVP03',
  HOME_VIEW_PRICING_UPDATE = 'HVP04',
  HOME_VIEW_PRICING_DELETE = 'HVP05',
  HOME_VIEW_PRICING_ORDER = 'HVP06',
  HOME_VIEW_PRICING_CHANGE_STATUS = 'HVP07',

  // HOME CONTACT US
  HOME_CONTACT_US_ALL = 'HCU00',
  HOME_CONTACT_US_FETCH = 'HCU01',
  HOME_CONTACT_US_DETAILS = 'HCU02',
  HOME_CONTACT_US_CREATE = 'HCU03',
  HOME_CONTACT_US_UPDATE = 'HCU04',
  HOME_CONTACT_US_DELETE = 'HCU05',
  HOME_CONTACT_US_ORDER = 'HCU06',
  HOME_CONTACT_US_CHANGE_STATUS = 'HCU07',

  // ABOUT US FEATURE
  ABOUT_US_FEATURE_ALL = 'AF00',
  ABOUT_US_FEATURE_FETCH = 'AF01',
  ABOUT_US_FEATURE_DETAILS = 'AF02',
  ABOUT_US_FEATURE_CREATE = 'AF03',
  ABOUT_US_FEATURE_UPDATE = 'AF04',
  ABOUT_US_FEATURE_DELETE = 'AF05',
  ABOUT_US_FEATURE_ORDER = 'AF06',
  ABOUT_US_FEATURE_CHANGE_STATUS = 'AF07',

  // ABOUT US CORE
  ABOUT_US_CORE_ALL = 'AC00',
  ABOUT_US_CORE_FETCH = 'AC01',
  ABOUT_US_CORE_DETAILS = 'AC02',
  ABOUT_US_CORE_CREATE = 'AC03',
  ABOUT_US_CORE_UPDATE = 'AC04',
  ABOUT_US_CORE_DELETE = 'AC05',
  ABOUT_US_CORE_ORDER = 'AC06',
  ABOUT_US_CORE_CHANGE_STATUS = 'AC07',

  // SERVICE
  SERVICE_ALL = 'SV00',
  SERVICE_FETCH = 'SV01',
  SERVICE_DETAILS = 'SV02',
  SERVICE_CREATE = 'SV03',
  SERVICE_UPDATE = 'SV04',
  SERVICE_DELETE = 'SV05',
  SERVICE_ORDER = 'SV06',
  SERVICE_CHANGE_STATUS = 'SV07',

  // SERVICE FEATURE
  SERVICE_FEATURE_ALL = 'SF00',
  SERVICE_FEATURE_FETCH = 'SF01',
  SERVICE_FEATURE_DETAILS = 'SF02',
  SERVICE_FEATURE_CREATE = 'SF03',
  SERVICE_FEATURE_UPDATE = 'SF04',
  SERVICE_FEATURE_DELETE = 'SF05',
  SERVICE_FEATURE_ORDER = 'SF06',
  SERVICE_FEATURE_CHANGE_STATUS = 'SF07',

  // SERVICE SECTION
  SERVICE_SECTION_ALL = 'SS00',
  SERVICE_SECTION_FETCH = 'SS01',
  SERVICE_SECTION_DETAILS = 'SS02',
  SERVICE_SECTION_CREATE = 'SS03',
  SERVICE_SECTION_UPDATE = 'SS04',
  SERVICE_SECTION_DELETE = 'SS05',
  SERVICE_SECTION_ORDER = 'SS06',
  SERVICE_SECTION_CHANGE_STATUS = 'SS07',

  // SERVICE LOG
  SERVICE_LOG_ALL = 'SL00',
  SERVICE_LOG_FETCH = 'SL01',
  SERVICE_LOG_DETAILS = 'SL02',
  SERVICE_LOG_CREATE = 'SL03',
  SERVICE_LOG_UPDATE = 'SL04',
  SERVICE_LOG_DELETE = 'SL05',
  SERVICE_LOG_ORDER = 'SL06',
  SERVICE_LOG_CHANGE_STATUS = 'SL07',

  // SERVICE KEY
  SERVICE_KEY_ALL = 'SK00',
  SERVICE_KEY_FETCH = 'SK01',
  SERVICE_KEY_DETAILS = 'SK02',
  SERVICE_KEY_CREATE = 'SK03',
  SERVICE_KEY_UPDATE = 'SK04',
  SERVICE_KEY_DELETE = 'SK05',
  SERVICE_KEY_ORDER = 'SK06',
  SERVICE_KEY_CHANGE_STATUS = 'SK07',

  // CLIENT OPINION
  CLIENT_OPINION_ALL = 'CO00',
  CLIENT_OPINION_FETCH = 'CO01',
  CLIENT_OPINION_DETAILS = 'CO02',
  CLIENT_OPINION_CREATE = 'CO03',
  CLIENT_OPINION_UPDATE = 'CO04',
  CLIENT_OPINION_DELETE = 'CO05',
  CLIENT_OPINION_ORDER = 'CO06',
  CLIENT_OPINION_CHANGE_STATUS = 'CO07',

  // REQUEST SERVICE
  REQUEST_SERVICE_ALL = 'RS00',
  REQUEST_SERVICE_FETCH = 'RS01',
  REQUEST_SERVICE_DETAILS = 'RS02',
  REQUEST_SERVICE_DELETE = 'RS03',

  // WEBSITE INFO
  WEBSITE_INFO_ALL = 'WI00',
  WEBSITE_INFO_FETCH = 'WI01',
  WEBSITE_INFO_DETAILS = 'WI02',
  WEBSITE_INFO_CREATE = 'WI03',
  WEBSITE_INFO_UPDATE = 'WI04',
  WEBSITE_INFO_DELETE = 'WI05',
  WEBSITE_INFO_ORDER = 'WI06',
  WEBSITE_INFO_CHANGE_STATUS = 'WI07',

  // CONTACT US
  CONTACT_US_ALL = 'CU00',
  CONTACT_US_FETCH = 'CU01',
  CONTACT_US_DETAILS = 'CU02',
  CONTACT_US_DELETE = 'CU03',

  // OUR SYSTEM BANNER
  OUR_SYSTEM_BANNER_ALL = 'OSB00',
  OUR_SYSTEM_BANNER_FETCH = 'OSB01',
  OUR_SYSTEM_BANNER_DETAILS = 'OSB02',
  OUR_SYSTEM_BANNER_CREATE = 'OSB03',
  OUR_SYSTEM_BANNER_UPDATE = 'OSB04',
  OUR_SYSTEM_BANNER_DELETE = 'OSB05',
  OUR_SYSTEM_BANNER_ORDER = 'OSB06',
  OUR_SYSTEM_BANNER_CHANGE_STATUS = 'OSB07',

  // OUR SYSTEM FEATURE
  OUR_SYSTEM_FEATURE_ALL = 'OSF00',
  OUR_SYSTEM_FEATURE_FETCH = 'OSF01',
  OUR_SYSTEM_FEATURE_DETAILS = 'OSF02',
  OUR_SYSTEM_FEATURE_CREATE = 'OSF03',
  OUR_SYSTEM_FEATURE_UPDATE = 'OSF04',
  OUR_SYSTEM_FEATURE_DELETE = 'OSF05',
  OUR_SYSTEM_FEATURE_ORDER = 'OSF06',
  OUR_SYSTEM_FEATURE_CHANGE_STATUS = 'OSF07',

  // OUR SYSTEM RISK MANAGEMENT
  OUR_SYSTEM_RISK_MANAGEMENT_ALL = 'OSRM00',
  OUR_SYSTEM_RISK_MANAGEMENT_FETCH = 'OSRM01',
  OUR_SYSTEM_RISK_MANAGEMENT_DETAILS = 'OSRM02',
  OUR_SYSTEM_RISK_MANAGEMENT_CREATE = 'OSRM03',
  OUR_SYSTEM_RISK_MANAGEMENT_UPDATE = 'OSRM04',
  OUR_SYSTEM_RISK_MANAGEMENT_DELETE = 'OSRM05',
  OUR_SYSTEM_RISK_MANAGEMENT_ORDER = 'OSRM06',
  OUR_SYSTEM_RISK_MANAGEMENT_CHANGE_STATUS = 'OSRM07',

  // OUR SYSTEM RISK TYPE
  OUR_SYSTEM_RISK_TYPE_ALL = 'OSRT00',
  OUR_SYSTEM_RISK_TYPE_FETCH = 'OSRT01',
  OUR_SYSTEM_RISK_TYPE_DETAILS = 'OSRT02',
  OUR_SYSTEM_RISK_TYPE_CREATE = 'OSRT03',
  OUR_SYSTEM_RISK_TYPE_UPDATE = 'OSRT04',
  OUR_SYSTEM_RISK_TYPE_DELETE = 'OSRT05',
  OUR_SYSTEM_RISK_TYPE_ORDER = 'OSRT06',
  OUR_SYSTEM_RISK_TYPE_CHANGE_STATUS = 'OSRT07',

  // OUR SYSTEM COMPONENT
  OUR_SYSTEM_COMPONENT_ALL = 'OSC00',
  OUR_SYSTEM_COMPONENT_FETCH = 'OSC01',
  OUR_SYSTEM_COMPONENT_DETAILS = 'OSC02',
  OUR_SYSTEM_COMPONENT_CREATE = 'OSC03',
  OUR_SYSTEM_COMPONENT_UPDATE = 'OSC04',
  OUR_SYSTEM_COMPONENT_DELETE = 'OSC05',
  OUR_SYSTEM_COMPONENT_ORDER = 'OSC06',
  OUR_SYSTEM_COMPONENT_CHANGE_STATUS = 'OSC07',

  // OUR SYSTEM STEP
  OUR_SYSTEM_STEP_ALL = 'OSS00',
  OUR_SYSTEM_STEP_FETCH = 'OSS01',
  OUR_SYSTEM_STEP_DETAILS = 'OSS02',
  OUR_SYSTEM_STEP_CREATE = 'OSS03',
  OUR_SYSTEM_STEP_UPDATE = 'OSS04',
  OUR_SYSTEM_STEP_DELETE = 'OSS05',
  OUR_SYSTEM_STEP_ORDER = 'OSS06',
  OUR_SYSTEM_STEP_CHANGE_STATUS = 'OSS07',

  // FAQ
  FAQ_ALL = 'FQ00',
  FAQ_FETCH = 'FQ01',
  FAQ_DETAILS = 'FQ02',
  FAQ_CREATE = 'FQ03',
  FAQ_UPDATE = 'FQ04',
  FAQ_DELETE = 'FQ05',
  FAQ_ORDER = 'FQ06',
  FAQ_CHANGE_STATUS = 'FQ07',

  // TERM
  TERM_ALL = 'TM00',
  TERM_FETCH = 'TM01',
  TERM_CREATE_OR_UPDATE = 'TM02',

  // PRIVACY
  PRIVACY_ALL = 'PR00',
  PRIVACY_FETCH = 'PR01',
  PRIVACY_CREATE_OR_UPDATE = 'PR02',

  // HEADER TITLE
  HEADER_TITLE_ALL = 'HTW00',
  HEADER_TITLE_FETCH = 'HTW01',
  HEADER_TITLE_CREATE_OR_UPDATE = 'HTW02',

  CREATE_PERMISSION = 'CP00',

  // Template Item
  TEMPLATE_ITEM_ALL = 'TI00',
  TEMPLATE_ITEM_FETCH = 'TI01',
  TEMPLATE_ITEM_DETAILS = 'TI02',
  TEMPLATE_ITEM_CREATE = 'TI03',
  TEMPLATE_ITEM_UPDATE = 'TI04',
  TEMPLATE_ITEM_DELETE = 'TI05',

  // // contractor  CONTRACTOR_ALL = 'CTR00',
  // CONTRACTOR_All = 'OCTR00',
  // CONTRACTOR_FETCH = 'OCTR01',
  // CONTRACTOR_DETAILS = 'OCTR02',
  // CONTRACTOR_CREATE = 'OCTR03',
  // CONTRACTOR_UPDATE = 'OCTR04',
  // CONTRACTOR_DELETE = 'OCTR05',

  // observation type
  OBSERVATION_TYPE_ALL = 'OBT00',
  OBSERVATION_TYPE_FETCH = 'OBT01',
  OBSERVATION_TYPE_DETAILS = 'OBT02',
  OBSERVATION_TYPE_CREATE = 'OBT03',
  OBSERVATION_TYPE_UPDATE = 'OBT04',
  OBSERVATION_TYPE_DELETE = 'OBT05',

  // observation type
  ORG_OBSERVATION_TYPE_ALL = 'OOBT00',
  ORG_OBSERVATION_TYPE_FETCH = 'OOBT01',
  ORG_OBSERVATION_TYPE_DETAILS = 'OOBT02',
  ORG_OBSERVATION_TYPE_CREATE = 'OOBT03',
  ORG_OBSERVATION_TYPE_UPDATE = 'OOBT04',
  ORG_OBSERVATION_TYPE_DELETE = 'OOBT05',

  // ORG OBSERVATION
  ORG_OBSERVATION_ALL = 'OOB00',
  ORG_OBSERVATION_FETCH = 'OOB01',
  ORG_OBSERVATION_DETAILS = 'OOB02',
  ORG_OBSERVATION_CREATE = 'OOB03',
  ORG_OBSERVATION_UPDATE = 'OOB04',
  ORG_OBSERVATION_DELETE = 'OOB05',

  // healthconditions
  HEALTH_CONDITION_ALL = 'OHC00',
  HEALTH_CONDITION_FETCH = 'OHC01',
  HEALTH_CONDITION_DETAILS = 'OHC02',
  HEALTH_CONDITION_CREATE = 'OHC03',
  HEALTH_CONDITION_UPDATE = 'OHC04',
  HEALTH_CONDITION_DELETE = 'OHC05',

  // healthconditions
  ORG_HEALTH_CONDITION_ALL = 'OOHC00',
  ORG_HEALTH_CONDITION_FETCH = 'OOHC01',
  ORG_HEALTH_CONDITION_DETAILS = 'OOHC02',
  ORG_HEALTH_CONDITION_CREATE = 'OOHC03',
  ORG_HEALTH_CONDITION_UPDATE = 'OOHC04',
  ORG_HEALTH_CONDITION_DELETE = 'OOHC05',

  // Organization Contractor
  ORG_CONTRACTOR_ALL = 'OOC00',
  ORG_CONTRACTOR_FETCH = 'OOC01',
  ORG_CONTRACTOR_DETAILS = 'OOC02',
  ORG_CONTRACTOR_CREATE = 'OOC03',
  ORG_CONTRACTOR_UPDATE = 'OOC04',
  ORG_CONTRACTOR_DELETE = 'OOC05',

  // Organization Equipment Management
  ORG_EQUIPMENT_MANGEMENT_ALL = 'OOEM00',
  ORG_EQUIPMENT_MANGEMENT_FETCH = 'OOEM01',
  ORG_EQUIPMENT_MANGEMENT_DETAILS = 'OOEM02',
  ORG_EQUIPMENT_MANGEMENT_CREATE = 'OOEM03',
  ORG_EQUIPMENT_MANGEMENT_UPDATE = 'OOEM04',
  ORG_EQUIPMENT_MANGEMENT_DELETE = 'OOEM05',
}
