export enum ProjectProgressStatusEnum {
  BASIC_DATA = 1,
  BASIC_DATA_AND_HOLIDAYS = 2,
  BASIC_DATA_AND_HOLIDAYS_AND_POSITIONS_AND_EMPLOYEES = 3,
  BASIC_DATA_AND_HOLIDAYS_AND_POSITIONS_AND_EMPLOYEES_AND_TEAMS = 4,
  BASIC_DATA_AND_HOLIDAYS_AND_POSITIONS_AND_EMPLOYEES_AND_TEAMS_AND_EQUIPMENT = 5,
}

