export enum NotificationPlanActionEnum {
  TASK_ASSIGNED = 1,
  PROJECT_LOCATION_HIERARCHY_ASSIGNMENT = 3,
  OBSERVATION_CREATED = 4,
  INVESTIGATION_TASK_CREATED = 11,
  INVESTIGATION_TASK_STATUS_CHANGED = 12,
  INVESTIGATION_TEAM_ADDED = 13,
}
